site_name: OGC API Processes with ZOO-Project

theme:
    
    name: material
    icon: 
      logo: fontawesome/solid/earth-europe
    palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
plugins:
  - search
  - swagger-ui-tag:
      filter: true
      tryItOutEnabled: false
  - mermaid2:
      version: 10.6.0

markdown_extensions:
  - pymdownx.details
  - abbr
  - admonition
  - footnotes
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences: 
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - pymdownx.snippets:
      base_path: './'
  - pymdownx.highlight:
      line_spans: __span
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_css:
  - styles/css/app.css
  
extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  

nav:
  - Introduction: 'index.md'
  - Local installation: 'installation.md'
  - Execution Scenario: execution-scenario.md
  - Introducing the application:
    - Water bodies detection: app/water-bodies-detection.md
  - Deploy and run the EO application:
    - Deploy the application: deploy-application.md
    - List available processes: list-processes.md
    - Describe the process: describe-process.md
    - Execute and monitor the process: execute-monitor-process.md 
  - Package the EO application CLI:
    - Creating the containers: 
      - Scope: containers/scope.md
      - Build and test the containers:
        - OGC API Process Client: containers/ogc_api_processes_client.md
    - Create CWL CommandLineTools:
      - Scope: cwl-cli/scope.md
      - Prepare Execute Request CommandLineTool: cwl-cli/prepare-execute.md
      - OGC API Process Client CommandLineTool: cwl-cli/ogc-api-processes-client.md
    - Create the CWL Workflows:
      - Scope: cwl-workflow/scope.md
      - EO application API Workflow: cwl-workflow/eoap-api.md
    - Run OGC API Process Application Package: cwl-workflow/run-workflow.md
  - Reference:
    - OGC API Processes: reference/ogc-api-processes.md
    - OGC API Processes OpenAPI: reference/ogc-api-processes-openapi.md
    - ZOO-Project: reference/zoo-project.md

copyright: <a href="https://img.shields.io/badge/License-CC_BY--SA_4.0-lightgrey.svg">License CC BY-SA 4.0</a>, by <a href="https://creativecommons.org/licenses/by-sa/4.0/">Creative Commons</a>